[tool.poetry]
name = "postgrest-py"
description = "PostgREST client for Python. This library provides an ORM interface to PostgREST."
version = "0.6.0"
authors = ["Lương Quang Mạnh <luongquangmanh85@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/supabase/postgrest-py"
repository = "https://github.com/supabase/postgrest-py"

[tool.poetry.dependencies]
python = "^3.7"
httpx = ">=0.19,<0.22"
deprecation = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-asyncio = "^0.16.0"
pytest-cov = "^3.0.0"
mypy = "^0.910"
black = { version = "^21.11b1", allow-prereleases = true }
pre-commit = "^2.16.0"
unasync-cli = "^0.0.9"

[tool.black]
line-length = 90

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
